### ISSUE TITLE
강의 01 운영체제가 뭐길래? | 교재 해당 없음

### ISSUE THREAD

**Issue by develiberta** [study-with-book/study-os#1]

**Comment by Su-Gyeong3489** [comment]
https://beautiful-tendency-40a.notion.site/20220903-a37c9ed06d0f436cbba1931cbdf0395c

**Comment by lhrm** [comment]
https://lhrm-study.notion.site/Operating-System-e465600578a24c7e902155ccf9bc9e67

**Comment by pengduck** [comment]
https://pengduck.github.io/posts/post_20220903_wsl/

https://pengduck.github.io/posts/post_20220904_os_intro/

**Comment by develiberta** [comment]
https://develiberta.github.io/posts/os-getting-started/
https://develiberta.github.io/posts/os-definition/
