### ISSUE TITLE
강의 11 프로세스 동기화 | 교재 Chapter 6 Synchronization Tools 6.1 ~ 6.2

### ISSUE THREAD

**Issue by develiberta** [study-with-book/study-os#10]

**Comment by lhrm** [comment]
https://lhrm-study.notion.site/Process-Synchronization-6-1-6-2-8b068e5f27964d18ba3a47d9486b14b1

**Comment by pengduck** [comment]
https://pengduck.github.io/posts/post_20221111_os_synchronization_tools/?v=1668231948

**Comment by Su-Gyeong3489** [comment]
https://beautiful-tendency-40a.notion.site/10-85bb62145ea24265bd85f582ddb6bc37

**Comment by develiberta** [comment]
https://develiberta.github.io/posts/os-synchronization-tools-01/
