### ISSUE TITLE
강의 12 동기화 문제의 해결책 | 교재 Chapter 6 Synchronization Tools 6.3 ~ 6.4

### ISSUE THREAD

**Issue by develiberta** [study-with-book/study-os#11]

**Comment by Su-Gyeong3489** [comment]
https://beautiful-tendency-40a.notion.site/11-44093bf4d7e84f0ea07de4e4b167b2cc

**Comment by lhrm** [comment]
https://lhrm-study.notion.site/Chapter-6-Synchronization-Tools-6-3-6-4-2c1217375d3b4975a304896305b6a5b7

**Comment by pengduck** [comment]
https://pengduck.github.io/posts/post_20221111_os_synchronization_tools/?v=1668768419

**Comment by develiberta** [comment]
https://develiberta.github.io/posts/os-synchronization-tools/
