### ISSUE TITLE
 강의 13 뮤텍스와 세마포어 | 교재 Chapter 6 Synchronization Tools 6.5 ~ 6.6

### ISSUE THREAD

**Issue by develiberta** [study-with-book/study-os#13]

**Comment by Su-Gyeong3489** [comment]
https://beautiful-tendency-40a.notion.site/13-9f5802b64f024b87b9b112e422544103

**Comment by lhrm** [comment]
https://lhrm-study.notion.site/Chapter-6-Synchronization-Tools-6-5-6-6-748a0337a7fa4b528a10d3b6bf26a9af

**Comment by pengduck** [comment]
https://pengduck.github.io/posts/post_20221111_os_synchronization_tools/?v=1670760630

**Comment by develiberta** [comment]
https://develiberta.github.io/posts/os-synchronization-tools/
