### ISSUE TITLE
강의 14 모니터와 자바 동기화 | 교재 Chapter 6 Synchronization Tools 6.7 ~ 6.10

### ISSUE THREAD

**Issue by develiberta** [study-with-book/study-os#14]

**Comment by Su-Gyeong3489** [comment]
https://beautiful-tendency-40a.notion.site/14-5284e32f6b434b3d810d110961b82281

**Comment by lhrm** [comment]
https://lhrm-study.notion.site/Chapter-6-Synchronization-Tools-6-7-6-10-f944dfaaa9fc4becaedbc3b1a3922996

**Comment by develiberta** [comment]
https://develiberta.github.io/posts/os-synchronization-tools/

**Comment by pengduck** [comment]
https://pengduck.github.io/posts/post_20221111_os_synchronization_tools/?v=1671361261
