### ISSUE TITLE
강의 15 동시성 제어의 고전적 문제들 | 교재 Chapter 7 Synchronization Examples 7.1

### ISSUE THREAD

**Issue by develiberta** [study-with-book/study-os#15]

**Comment by pengduck** [comment]
https://pengduck.github.io/posts/post_20221225_os_synchronization_ex/?v=1671956999

**Comment by develiberta** [comment]
https://develiberta.github.io/posts/os-synchronization-examples/

**Comment by lhrm** [comment]
https://lhrm-study.notion.site/Chapter-7-e0d793c9490541fea3c7a5456a6ecba9

**Comment by Su-Gyeong3489** [comment]
https://beautiful-tendency-40a.notion.site/15-e11f8d5852944552ba0ee24be3c5c02b
