### ISSUE TITLE
강의 16 철학자들은 왜 굶어 죽었을까? | 교재 Chapter 7 Synchronization Examples 7.1 ~ 7.5

### ISSUE THREAD

**Issue by develiberta** [study-with-book/study-os#16]

**Comment by pengduck** [comment]
https://pengduck.github.io/posts/post_20221225_os_synchronization_ex/?v=1673179036

**Comment by develiberta** [comment]
https://develiberta.github.io/posts/os-synchronization-examples/

**Comment by lhrm** [comment]
https://lhrm-study.notion.site/16-7a76f8c777db493f8de6ae9153a680d5

**Comment by Su-Gyeong3489** [comment]
https://beautiful-tendency-40a.notion.site/16-7d062fc0bbfb41978627ecf3badf29ec
