### ISSUE TITLE
강의 17 데드락의 이해 | 교재 Chapter 8 Deadlocks 8.1 ~ 8.5

### ISSUE THREAD

**Issue by develiberta** [study-with-book/study-os#17]

**Comment by lhrm** [comment]
https://lhrm-study.notion.site/Chapter-8-Deadlocks-8-1-8-5-2cfea637de7e400db7daccf0296cca0b

**Comment by pengduck** [comment]
https://pengduck.github.io/posts/post_deadlock/?v=1673782478

**Comment by develiberta** [comment]
https://develiberta.github.io/posts/os-deadlocks/?v=1673785320
