### ISSUE TITLE
강의 18 데드락과 뱅커 알고리즘 | 교재 Chapter 8 Deadlocks 8.6 ~ 8.9

### ISSUE THREAD

**Issue by develiberta** [study-with-book/study-os#18]

**Comment by Su-Gyeong3489** [comment]
https://beautiful-tendency-40a.notion.site/17-18-3470accd9c0f46ebb701c93a09299dd4

**Comment by lhrm** [comment]
https://lhrm-study.notion.site/Chapter-8-Deadlocks-8-6-8-9-6e7165422ed043a2803cca19336a737f

**Comment by pengduck** [comment]
https://pengduck.github.io/posts/post_deadlock/?v=1674994356

**Comment by develiberta** [comment]
https://develiberta.github.io/posts/os-deadlocks/?v=1673785320
