### ISSUE TITLE
강의 02 운영체제의 개념과 구조 | 교재 Chapter 1-2 Introduction & O/S structures

### ISSUE THREAD

**Issue by develiberta** [study-with-book/study-os#2]

**Comment by develiberta** [comment]
https://develiberta.github.io/posts/os-introduction/

**Comment by lhrm** [comment]
https://lhrm-study.notion.site/Operating-System-e465600578a24c7e902155ccf9bc9e67

**Comment by pengduck** [comment]
https://pengduck.github.io/posts/post_20220916_os_overview/

https://pengduck.github.io/posts/post_20220917_os_structures/

**Comment by Su-Gyeong3489** [comment]
https://beautiful-tendency-40a.notion.site/2-254099d57c6c420f85506d39800e9c50
