### ISSUE TITLE
강의 20 페이징과 스와핑 | 교재 Chapter 9 Main Memory 9.3 ~ 9.5

### ISSUE THREAD

**Issue by develiberta** [study-with-book/study-os#20]

**Comment by develiberta** [comment]
https://develiberta.github.io/posts/os-main-memory/?v=1675755823

**Comment by pengduck** [comment]
https://pengduck.github.io/posts/os_main_memory/?v=1676202238

**Comment by lhrm** [comment]
https://lhrm-study.notion.site/Chapter-9-Main-Memory-9-3-9-5-b43a15b6e1364cd08cd61239092a7785

**Comment by Su-Gyeong3489** [comment]
https://beautiful-tendency-40a.notion.site/20-6960b5856e5b4e1b9deabe95a9c23cb5
