### ISSUE TITLE
강의 22 페이지 교체 알고리즘 | 교재 Chapter 10 Virtual Memory 10.4 ~ 10.11

### ISSUE THREAD

**Issue by develiberta** [study-with-book/study-os#22]

**Comment by lhrm** [comment]
https://lhrm-study.notion.site/Chapter-10-Virtual-Memory-10-4-10-11-a8edbdbb527241fa8f2bddb0d51c5b9d

**Comment by pengduck** [comment]
https://pengduck.github.io/posts/os_virtual_memory/?v=1677413322

**Comment by develiberta** [comment]
https://develiberta.github.io/posts/os-virtual-memory/?v=1676811081
