### ISSUE TITLE
강의 23 스토리지와 입출력 | 교재 Chapter 11-15 Storage Management

### ISSUE THREAD

**Issue by develiberta** [study-with-book/study-os#23]

**Comment by lhrm** [comment]
https://lhrm-study.notion.site/Chapter-11-14-Storage-Management-5b97f57eb05c41feb9a51077dd5f0b8b

**Comment by Su-Gyeong3489** [comment]
https://beautiful-tendency-40a.notion.site/23-e5748864686f43ccb0b380a9efac0c7e

**Comment by develiberta** [comment]
https://develiberta.github.io/posts/os-storage-management/?v=1678019406
