### ISSUE TITLE
강의 24 운영체제의 보안 | 교재 Chapter 16-17 Security & Protection

### ISSUE THREAD

**Issue by develiberta** [study-with-book/study-os#24]

**Comment by pengduck** [comment]
https://pengduck.github.io/posts/os_security/?v=1678714580
https://pengduck.github.io/posts/os_protection/?v=1678714580

**Comment by lhrm** [comment]
https://lhrm-study.notion.site/Chapter-16-17-Security-Protection-ce051ca72c9c48d8815ff8325d0318eb

**Comment by develiberta** [comment]
https://develiberta.github.io/posts/os-security/?v=1678796353
https://develiberta.github.io/posts/os-protection/?v=1678796353

**Comment by Su-Gyeong3489** [comment]
https://beautiful-tendency-40a.notion.site/24-4158147cdb334c299d6a872d7ddf3fc1
