### ISSUE TITLE
강의 06 프로세스간 통신의 실제 | 교재 Chapter 3 Processes 3.7 ~ 3.8

### ISSUE THREAD

**Issue by develiberta** [study-with-book/study-os#5]

**Comment by pengduck** [comment]
https://pengduck.github.io/posts/post_20220923_os_process/?v=1665357812

**Comment by lhrm** [comment]
https://lhrm-study.notion.site/1ad2a516f07d4833ba6db92c06b8a528

**Comment by Su-Gyeong3489** [comment]
https://beautiful-tendency-40a.notion.site/5-e3c79a6657ff4de6a1c0a8dc9b76027c

**Comment by develiberta** [comment]
https://develiberta.github.io/posts/os-process-03/
