### ISSUE TITLE
강의 07 쓰레드의 이해 | 교재 Chapter 4 Thread & Concurrency 4.1 ~ 4.2

### ISSUE THREAD

**Issue by develiberta** [study-with-book/study-os#6]

**Comment by lhrm** [comment]
https://lhrm-study.notion.site/Thread-Currency-6411037386aa4490a45ce92588f063ec

**Comment by develiberta** [comment]
https://develiberta.github.io/posts/os-thread-01/

**Comment by pengduck** [comment]
https://pengduck.github.io/posts/post_20221015_os_thread/?v=1665889662

**Comment by Su-Gyeong3489** [comment]
https://beautiful-tendency-40a.notion.site/6-f4597a7b6abb4772aaa38ca8d526ddf1
