### ISSUE TITLE
강의 08 멀티쓰레딩 | 교재 Chapter 4 Thread & Concurrency 4.3 ~ 4.5

### ISSUE THREAD

**Issue by develiberta** [study-with-book/study-os#7]

**Comment by develiberta** [comment]
https://develiberta.github.io/posts/os-thread-02/

**Comment by pengduck** [comment]
https://pengduck.github.io/posts/post_20221015_os_thread/?v=1666501717

**Comment by lhrm** [comment]
https://lhrm-study.notion.site/Thread-Currency-4-3-4-5-2bf2f4311daf47bb89cb2a304844d402

**Comment by Su-Gyeong3489** [comment]
https://beautiful-tendency-40a.notion.site/7-fc5a8de10e5d4f78a8f4f80d1ae54d83
