### ISSUE TITLE
강의 09 CPU 스케줄링 | 교재 Chapter 5 CPU Scheduling 5.1 ~ 5.3

### ISSUE THREAD

**Issue by develiberta** [study-with-book/study-os#8]

**Comment by pengduck** [comment]
https://pengduck.github.io/posts/post_20221026_os_cpu_scheduling/?v=1667019453

**Comment by lhrm** [comment]
https://lhrm-study.notion.site/CPU-Scheduling-5-1-5-3-df27afb70a4542468a216c1b4ef3b180

**Comment by Su-Gyeong3489** [comment]
https://beautiful-tendency-40a.notion.site/8-48e46baa39d147eb8b44895877b4c41f

**Comment by develiberta** [comment]
https://develiberta.github.io/posts/os-cpu-scheduling-01/
